// packages/templates/templates/sveltekit-web/src/lib/components/ui/input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils.js';

  type Props = HTMLInputAttributes & {
    class?: string;
    value?: string;
  };

  let { class: className, value = $bindable(''), ...restProps }: Props = $props();
</script>

<input
  class={cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    className
  )}
  bind:value
  {...restProps}
/>

// packages/templates/templates/expo-mobile/components/ui/Input.tsx
import { forwardRef } from 'react';
import { TextInput, TextInputProps } from 'react-native';
import { cn } from '@/lib/utils';

export interface InputProps extends TextInputProps {
  className?: string;
}

const Input = forwardRef<TextInput, InputProps>(
  ({ className, placeholderTextColor = '#64748b', ...props }, ref) => {
    return (
      <TextInput
        ref={ref}
        className={cn(
          'h-12 w-full rounded-md border border-input bg-background px-3 py-2 text-base text-foreground',
          'focus:border-ring',
          className
        )}
        placeholderTextColor={placeholderTextColor}
        {...props}
      />
    );
  }
);

Input.displayName = 'Input';

export { Input };
